### ISSUE TITLE
Expose trace IDs in cloud event functions

### ISSUE THREAD

**Issue by roffjulie** [GoogleCloudPlatform/functions-framework-dotnet#119]
The `X-Cloud-Trace-Context` header is included in requests, but as we don't expose headers to the event-style functions it is inaccessible. This value is the only means of grouping StackDriver logs by request, and so we should expose it to the user function code.

CloudEvents: The trace ID should be encoded as an extension on the event, leveraging the `traceparent` extension field as described in https://github.com/cloudevents/spec/blob/master/extensions/distributed-tracing.md.

**Comment by jskeet** [comment]
@juliehockett: Thinking about this more, I'd expect the CloudEvents SDKs to do the right thing in terms of regular conversion of HTTP requests to CloudEvents - and if they don't, we should fix them there, I'd suggest, rather than putting that logic into the FF. I may have missed something though, so please let me know.

That leaves conversion of existing GCF events to CloudEvents and including the header there, which I completely agree we should do.

**Comment by jskeet** [comment]
We're currently looking at including trace IDs in the console logger of Google.Cloud.Logging.Console. Doing the same thing in the FF *might* just unlock this...

**Comment by jskeet** [comment]
When #510 is merged, Kestrel's own handling of trace IDs (and request IDs) will be propagated via scopes. We *may* want to do more than this, but I *suspect* it's actually just going to work "out of the box".

I'm going to close this issue now as there's been little interest in it for 3.5 years. We can revisit with more precise requirements (which can then be evaluated against current behavior) if we need to.
