### ISSUE TITLE
.NET Core 5 support

### ISSUE THREAD

**Issue by jchannon** [GoogleCloudPlatform/functions-framework-dotnet#184]
Possibly not the best place to ask because it will require Google Cloud Functions to support v5 but is this a coming soon thing or a "we have to work on it for a few months" thing?

Thanks :)

**Comment by jskeet** [comment]
No promises about .NET 5, as it's not a LTS release. It may happen, but I wouldn't bank on it. I'm expecting .NET 6 (as the next LTS) to be supported soon after release.

**Comment by jskeet** [comment]
Forgot to say before: the Functions Framework itself *does* work with .NET 5, at least in my limited testing - so you could deploy your function to Cloud Run instead of GCF, just using your own Dockerfile. Not as slick as GCF support, of course, but it may be useful to know as an interim measure.

**Comment by SiliconOrchid** [comment]
Hi @jskeet   :-)

I was wondering whether advice regarding supported .NET-versions-with-GCF has been revised since your comments above, earlier in the year?  

I'm only interested in GCF, not looking to containerize! ;-)

For context, I'm in the middle of writing up a new blog series where I would like to demonstrate/compare how to pair up a simple Blazor app using corresponding http-triggered serverless solutions from each of the "big three".  

I'm hoping to provide correct advice in this article - and not be an idiot by not having done my homework properly and having missed some announcement that your team may have made about .NET 6 support etc!

For contrast, Azure has made available an option for an out-of-process worker process - that decouples function code from the platform.   This has got me speculating whether the folks at Google are doing something similar, or sticking to LTS versions on the platform?  (I appreciate that you may not be able to comment!)

Thankyou!

**Comment by jskeet** [comment]
Closing this now in favour of #229 - partly as .NET 5 is now out of support anyway.
