### ISSUE TITLE
Powershell Support

### ISSUE THREAD

**Issue by preston-hf** [GoogleCloudPlatform/functions-framework-dotnet#98]
Many IT organizations have a large human resources investment in people that know Powershell. AWS Lambda and of course Azure Functions both support Powershell scripts for functions. GCF should as well. If it's easy enough to add a template and make it work, Google should. I don't have any data but I expect that Powershell has way more users than F# and VB.NET combined.

**Comment by jskeet** [comment]
I can look into it, but with almost zero PowerShell experience, I'm not convinced I'll be able to give an idiomatic solution - and I suspect it will take a significant amount of time to investigate.

Could I ask whether this is speculative, or whether it's because you specifically *want* to use GCF from PowerShell? I definitely appreciate the suggestion, but I don't want to spend time on something that we don't have evidence that customers definitely want.

**Comment by preston-hf** [comment]
I don't personally have a Powershell script to host on GCF right now, and I could always deploy to Cloud Run. However, I know multiple groups that do use Powershell quite heavily for IT tasks and use similar functionality in AWS and Azure. GCP itself has invested a significant amount into [Cloud tools for PowerShell](https://cloud.google.com/powershell), and for quick and dirty IT tasks that you need to expose via HTTP, PowerShell is a great choice. Without PowerShell support you exclude a lot of staff in modern Windows IT orgs which know PowerShell quite well but not much else. You could probably just offer a similar compromise to F# for now. It's not idiomatic but it works and the template can always be improved over time.

**Comment by jskeet** [comment]
The difference between PowerShell support and F# support is that F# support only involves getting enough templating done so that "dotnet run" works. I *expect* that PowerShell will require an entirely separate build pack and potentially a different runtime. That doesn't mean we don't want to do it - just that I expect it to be a very significantly different amount of work, unless PowerShell now supports the .NET Core CLI in a way that I'm unfamiliar with. Will investigate when I get a chance, but no promises.

**Comment by jskeet** [comment]
Closing for now as we haven't had significant interest in this, and don't intend to pursue it at this time. We will revisit the decision if there's significant customer demand, of course.
